export interface ProjectConfig { roots: string[]; include: string; exclude: string; languageOverrides: string; preview: "secure" | "external"; tools: string[] }
const key = (root: string) => `klickrr.project.${root}`;
const WORKSPACES_KEY = "klickrr.workspaces.v1";
export interface ProjectWorkspace { name: string; roots: string[]; updated: number }
export function loadWorkspaces(): ProjectWorkspace[] { try { return JSON.parse(localStorage.getItem(WORKSPACES_KEY) ?? "[]") as ProjectWorkspace[]; } catch { return []; } }
function saveWorkspaces(items: ProjectWorkspace[]): void { localStorage.setItem(WORKSPACES_KEY, JSON.stringify(items)); }
export function loadProject(root: string): ProjectConfig { try { return { roots: [root], include: "", exclude: "", languageOverrides: "", preview: "secure", tools: [], ...JSON.parse(localStorage.getItem(key(root)) ?? "{}") }; } catch { return { roots: [root], include: "", exclude: "", languageOverrides: "", preview: "secure", tools: [] }; } }
export function openProjectConfig(root: string): void {
  const config = loadProject(root); const overlay = document.createElement("div"); overlay.className = "modal-overlay"; const modal = document.createElement("div"); modal.className = "modal"; const h = document.createElement("h2"); h.textContent = "Project Configuration"; modal.appendChild(h);
  const fields: [keyof ProjectConfig, string][] = [["roots", "Root folders (comma-separated)"], ["include", "Include patterns"], ["exclude", "Exclude patterns"], ["languageOverrides", "Language overrides (ext=language)"], ["tools", "Enabled tool IDs (comma-separated)"]];
  for (const [field, label] of fields) { const row = document.createElement("label"); row.className = "settings-row"; row.textContent = label; const input = document.createElement("input"); input.value = Array.isArray(config[field]) ? (config[field] as string[]).join(",") : String(config[field]); input.addEventListener("input", () => { (config as unknown as Record<string, unknown>)[field] = Array.isArray(config[field]) ? input.value.split(",").map((v) => v.trim()).filter(Boolean) : input.value; }); row.appendChild(input); modal.appendChild(row); }
  const actions = document.createElement("div"); actions.className = "modal-actions"; const cancel = document.createElement("button"); cancel.textContent = "Cancel"; cancel.addEventListener("click", () => overlay.remove()); const save = document.createElement("button"); save.textContent = "Save"; save.className = "primary"; save.addEventListener("click", () => { localStorage.setItem(key(root), JSON.stringify(config)); overlay.remove(); }); actions.append(cancel, save); modal.appendChild(actions); overlay.appendChild(modal); document.body.appendChild(overlay);
}

export function openProjectManager(currentRoot: string, onOpen: (workspace: ProjectWorkspace) => void): void {
  const overlay = document.createElement("div"); overlay.className = "modal-overlay"; const modal = document.createElement("div"); modal.className = "modal productivity-modal";
  const title = document.createElement("h2"); title.textContent = "Project Workspaces"; const list = document.createElement("div"); list.className = "productivity-list";
  const actions = document.createElement("div"); actions.className = "modal-actions"; const add = document.createElement("button"); add.textContent = "Save Current Project"; const close = document.createElement("button"); close.textContent = "Close"; actions.append(add, close); modal.append(title, list, actions); overlay.appendChild(modal); document.body.appendChild(overlay);
  let items = loadWorkspaces(); const render = () => { list.replaceChildren(...items.map((workspace, index) => { const row = document.createElement("div"); row.className = "workspace-project-row"; const open = document.createElement("button"); open.className = "productivity-row"; open.textContent = workspace.name; open.title = workspace.roots.join("\n"); open.addEventListener("click", () => { onOpen(workspace); overlay.remove(); }); const del = document.createElement("button"); del.textContent = "×"; del.addEventListener("click", () => { items.splice(index, 1); saveWorkspaces(items); render(); }); row.append(open, del); return row; })); };
  add.addEventListener("click", () => { const name = window.prompt("Project name", currentRoot.split("/").pop() || "Project"); if (!name) return; const config = loadProject(currentRoot); items = [{ name, roots: config.roots.length ? config.roots : [currentRoot], updated: Date.now() }, ...items.filter((item) => item.name !== name)]; saveWorkspaces(items); render(); }); close.addEventListener("click", () => overlay.remove()); render();
}
